name: PMMPKahoot
version: 1.0.1
api: 5.0.0
main: r3pt1s\kahoot\Kahoot
author: r3pt1s
description: Kahoot-based minigame for PocketMine-MP

permissions:
  pmmpkahoot.publiclobby.create:
    default: op
    description: Permission to create public games
  pmmpkahoot.template.create:
    default: op
    description: Permission to create templates
  pmmpkahoot.command.main:
    default: true
    description: Main Command for PMMPKahoot
  pmmpkahoot.command.leave:
    default: true
    description: Leave a game