public-lobbies:
  needPermToCreate: true # Type "false" if your players don't need a permission to create public Kahoot games.

create-templates:
  needPermToCreate: true # Type "false" if your players don't need a permission to create templates.